services:
  nginx:
    build: ./nginx/
    ports:
      - "8000:80"
    volumes:
      - ./php/:/var/www/html/

  php:
    build: ./php/
    expose:
      - 9000
    volumes:
      - ./php/:/var/www/html/

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mobileapp
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "8001:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8002:80"

  minio:
    image: bitnami/minio:latest
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=fakepng
      - MINIO_ROOT_PASSWORD=fakepngasdfghjkl
      - MINIO_DEFAULT_BUCKETS=default
    ports:
      - "8003:9001"
      - "8004:9000"
